### ISSUE TITLE
push 2.12 to maven central

### ISSUE THREAD

**Issue by feleio** [maiha/http-mock#19]
Hi , wondering if it is ok to push push 2.12 to maven central? That will be very helpful. thanks

**Comment by maiha** [comment]
@feleio 
Thank you for playing with http-mock!
I've just published 2.12. It would be available in maven soon.

Thank you,

**Comment by maiha** [comment]
updated!
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22sc.ala%22%20http-mock

**Comment by feleio** [comment]
Thanks a lot
